name: CI

on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
  
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Run syntax check (linting)
        id: syntax_check
        run: |
          chmod +x makeme
          ./makeme --run-check
      
      - name: Update version code
        id: update_version
        run: |
          chmod +x makeme
          ./makeme --update-version
      
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: AXIM0S
          author_email: axonasif@gmail.com
          message: 'Update version code'
          add: './README.md ./core/version'
